name: Deployment of solution

on: 
  push:
    branches: [ioetDockerSolution]

jobs:
  avoid_redundant_deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Check if the solution is already deployed
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2 
        with: 
          node-version: "16"
      - name: Install Dev dependencies
        run: npm ci
      - name: Test
        run: npm test
  
  deploy:
    needs: [ test ]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: hernanx21/ioet-solution:latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }